version: '3.8'
services:
  db:
    image: mysql:latest
    env_file:
      - .envDB
    ports:
        - 3306:3306
  app:
    image: node:16
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
    volumes:
        - ./:/app/
    tty: true
    stdin_open: true